language: go
go: 
  - 1.1
  - tip
services: neo4j
notificaitons:
  email:
    recipients:
      jason.mcvetta@gmail.com
    on_success: change
    on_failure: always
before_script:
  - go get -v github.com/bmizerany/assert
  - go get -v github.com/jmcvetta/randutil
env:
  - NEO4J_VERSION="2.0.0-M03"
