language: go
go: 
  - 1.1
  - tip
notificaitons:
  email:
    recipients:
      jason.mcvetta@gmail.com
    on_success: change
    on_failure: always
before_script:
  - go get -v github.com/bmizerany/assert
  - go get -v github.com/jmcvetta/randutil
#
# Lines below copied from # https://github.com/versae/neo4j-rest-client/blob/master/.travis.yml
#
before_install:
  - export NEO4J_PORT="7474"
  - sudo service neo4j stop || true
  - sleep 3
  - ./install_local_neo4j.bash $NEO4J_VERSION
  - ./lib/neo4j/bin/neo4j start || ( cat ./lib/neo4j/data/log/*.log && exit 1 )
  - curl http://localhost:$NEO4J_PORT/db/data/
  - curl -X DELETE 'http://localhost:7474/cleandb/supersecretdebugkey!'
env:
  - NEO4J_VERSION="2.0.0-RC1"
